const actionTypes = {
  GET_USER_LIST_SUCCESS : 'GET_USER_LIST_SUCCESS',
  ADD_USER_SUCCESS : 'ADD_USER_SUCCESS',
  REGISTER_EXTERNAL_SUCCESS : 'REGISTER_EXTERNAL_SUCCESS',
  USER_UPDATE_SUCCESS : 'USER_UPDATE_SUCCESS',
  DELETE_LIST_SUCCESS : 'DELETE_LIST_SUCCESS',
  EDIT_USER_SUCCESS:'EDIT_USER_SUCCESS',
  USER_LOGIN:"USER_LOGIN",
  CLEAR_LOGIN:"CLEAR_LOGIN"
}

export default actionTypes;